# for development mode

version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 4173:4173
    environment:
      BACK_END_USER: http://user:5001
    networks:
      - app-network
    volumes:
      - ./client:/dev/client # local files mounting to volume (workdir)
      - /dev/client/node_modules # This line creates a named volume named node_modules for the /dev/client/node_modules directory inside the container

  # back end

  user:
    build:
      context: ./server/user
      dockerfile: Dockerfile.dev
    ports:
      - 5001:5001
    environment:
      DB_URL: mongodb://db
    networks:
      - app-network
    volumes:
      - ./server/user:/dev/user # local files mounting to volume (workdir)
      - /dev/user/node_modules # This line creates a named volume named node_modules for the /dev/user/node_modules directory inside the container
  db:
    image: mongo:7.0.4-jammy
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
    networks:
      - app-network

volumes:
  data-volume:
  node_modules:


networks:
  app-network:
    driver: bridge
