# for production mode

version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4173:4173
    environment:
      BACK_END: http://user:5001
    networks:
      - app-network

  # back end

  user:
    build:
      context: ./server/user
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      DB_URL: mongodb://db
    networks:
      - app-network
  db:
    image: mongo:7.0.4-jammy
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
    networks:
      - app-network

volumes:
  data-volume:


networks:
  app-network:
    driver: bridge
